"""
Domain Models — Pure Python value objects and data classes.

These represent the core business concepts of the quantitative platform.
They have NO dependencies on infrastructure (no SQLAlchemy, no FastAPI, no Polars).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from enum import StrEnum
from typing import Any

# ==============================================================================
# Enumerations
# ==============================================================================


class AssetClass(StrEnum):
    """Supported asset classes."""

    EQUITY = "equity"
    ETF = "etf"
    FIXED_INCOME = "fixed_income"
    COMMODITY = "commodity"
    CRYPTO = "crypto"
    FX = "fx"


class OrderSide(StrEnum):
    """Order direction."""

    BUY = "buy"
    SELL = "sell"


class OrderType(StrEnum):
    """Order type for execution."""

    MARKET = "market"
    LIMIT = "limit"


class OrderStatus(StrEnum):
    """Lifecycle status of an order."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class BacktestStatus(StrEnum):
    """Lifecycle status of a backtest run."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class SignalDirection(StrEnum):
    """Signal output from a strategy."""

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


class QualityCheckStatus(StrEnum):
    """Status of a data quality check."""

    PASSED = "PASSED"
    FAILED = "FAILED"
    WARNING = "WARNING"


class PortfolioConstructionMethod(StrEnum):
    """Supported portfolio weighting methods."""

    EQUAL_WEIGHT = "equal_weight"
    INVERSE_VOLATILITY = "inverse_volatility"
    VOLATILITY_TARGETING = "volatility_targeting"


class RiskVerdict(StrEnum):
    """Risk engine approval verdict for a portfolio."""

    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


# ==============================================================================
# Value Objects (immutable, no identity)
# ==============================================================================


@dataclass(frozen=True)
class TimeRange:
    """Represents a date range for data queries and backtests."""

    start: date
    end: date

    def __post_init__(self) -> None:
        if self.start > self.end:
            msg = f"start ({self.start}) must be <= end ({self.end})"
            raise ValueError(msg)

    @property
    def days(self) -> int:
        return (self.end - self.start).days


@dataclass(frozen=True)
class Bar:
    """A single OHLCV bar — the atomic unit of market data."""

    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    adjusted_close: float | None = None

    def __post_init__(self) -> None:
        if self.high < self.low:
            msg = f"high ({self.high}) < low ({self.low}) for {self.symbol} at {self.timestamp}"
            raise ValueError(msg)
        if self.close < 0 or self.open < 0:
            msg = f"Negative price for {self.symbol} at {self.timestamp}"
            raise ValueError(msg)


@dataclass(frozen=True)
class Signal:
    """A trading signal emitted by a strategy for a specific asset."""

    symbol: str
    direction: SignalDirection
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    strength: float = 1.0  # Normalized signal strength [-1, 1]
    metadata: dict[str, float] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not -1.0 <= self.strength <= 1.0:
            msg = f"Signal strength must be in [-1, 1], got {self.strength}"
            raise ValueError(msg)


# ==============================================================================
# Domain Entities (have identity)
# ==============================================================================


@dataclass
class Asset:
    """A tradeable asset in the platform universe."""

    id: uuid.UUID = field(default_factory=uuid.uuid4)
    symbol: str = ""
    name: str = ""
    asset_class: AssetClass = AssetClass.ETF
    exchange: str = ""
    currency: str = "USD"
    sector: str | None = None
    is_active: bool = True
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass
class Order:
    """An order generated by the portfolio/execution pipeline."""

    id: uuid.UUID = field(default_factory=uuid.uuid4)
    asset_symbol: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    limit_price: float | None = None
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    filled_at: datetime | None = None


@dataclass(frozen=True)
class Execution:
    """A fill resulting from an order execution."""

    id: uuid.UUID = field(default_factory=uuid.uuid4)
    order_id: uuid.UUID = field(default_factory=uuid.uuid4)
    fill_price: float = 0.0
    fill_quantity: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
    executed_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class Position:
    """A current holding in a portfolio."""

    asset_symbol: str = ""
    quantity: float = 0.0
    avg_entry_price: float = 0.0
    current_price: float = 0.0

    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price

    @property
    def unrealized_pnl(self) -> float:
        return self.quantity * (self.current_price - self.avg_entry_price)

    @property
    def weight(self) -> float:
        """Weight requires external portfolio value — placeholder."""
        return 0.0


@dataclass
class PortfolioState:
    """Snapshot of a portfolio at a point in time."""

    timestamp: datetime
    cash: float
    positions: dict[str, Position] = field(default_factory=dict)

    @property
    def total_equity(self) -> float:
        positions_value = sum(p.market_value for p in self.positions.values())
        return self.cash + positions_value

    @property
    def exposure(self) -> float:
        """Gross exposure as fraction of total equity."""
        equity = self.total_equity
        if equity == 0:
            return 0.0
        return sum(abs(p.market_value) for p in self.positions.values()) / equity


@dataclass(frozen=True)
class BacktestConfig:
    """Immutable configuration for a single backtest run — ensures reproducibility."""

    strategy_name: str
    strategy_version: str
    parameters: dict[str, float | int | str | bool]
    universe: list[str]
    time_range: TimeRange
    initial_cash: float = 100_000.0
    commission_rate_bps: float = 5.0  # basis points per trade
    slippage_rate_bps: float = 5.0  # basis points slippage
    execution_delay_bars: int = 1  # next-bar execution (anti look-ahead)
    frequency: str = "1d"
    git_commit_sha: str | None = None

    def __post_init__(self) -> None:
        if self.initial_cash <= 0:
            msg = "initial_cash must be positive"
            raise ValueError(msg)
        if self.execution_delay_bars < 1:
            msg = "execution_delay_bars must be >= 1 to prevent look-ahead bias"
            raise ValueError(msg)


@dataclass(frozen=True)
class BacktestResult:
    """Complete output of a backtest run."""

    config: BacktestConfig
    status: BacktestStatus
    equity_curve: list[float]
    returns: list[float]
    dates: list[datetime]
    orders: list[Order]
    executions: list[Execution]
    metrics: dict[str, float]
    execution_time_ms: int = 0


# ==============================================================================
# Data Quality Models
# ==============================================================================


@dataclass(frozen=True)
class DataQualityCheckResult:
    """Result of an individual data quality check."""

    check_name: str
    status: QualityCheckStatus
    message: str
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class DataQualityReport:
    """Aggregate data quality validation report for a dataset/symbol."""

    dataset: str
    symbol: str
    status: QualityCheckStatus
    rows_checked: int
    checks: list[DataQualityCheckResult] = field(default_factory=list)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def is_valid(self) -> bool:
        return self.status == QualityCheckStatus.PASSED

    @property
    def errors(self) -> list[str]:
        return [c.message for c in self.checks if c.status == QualityCheckStatus.FAILED]

    @property
    def check_summary(self) -> dict[str, str]:
        return {c.check_name: c.status.value for c in self.checks}


# ==============================================================================
# Portfolio Engine Models
# ==============================================================================


@dataclass(frozen=True)
class PortfolioConstraints:
    """Configurable limits for portfolio construction."""

    max_position_weight: float = 0.25  # Max absolute weight per asset (e.g. 25%)
    max_gross_exposure: float = 1.00  # Max sum of absolute weights (e.g. 100%)
    max_turnover: float = 0.50  # Max rebalance turnover per step
    target_volatility: float | None = None  # Optional annual volatility target

    def __post_init__(self) -> None:
        if self.max_position_weight <= 0 or self.max_position_weight > 1.0:
            msg = f"max_position_weight must be in (0, 1], got {self.max_position_weight}"
            raise ValueError(msg)
        if self.max_gross_exposure <= 0:
            msg = f"max_gross_exposure must be positive, got {self.max_gross_exposure}"
            raise ValueError(msg)
        if self.max_turnover <= 0:
            msg = f"max_turnover must be positive, got {self.max_turnover}"
            raise ValueError(msg)


@dataclass(frozen=True)
class TargetWeights:
    """Target portfolio weights output by PortfolioEngine."""

    weights: dict[str, float]  # symbol -> target weight [-1.0, 1.0]
    timestamp: datetime
    method: PortfolioConstructionMethod
    turnover: float = 0.0
    metadata: dict[str, float | str] = field(default_factory=dict)

    @property
    def gross_exposure(self) -> float:
        return sum(abs(w) for w in self.weights.values())

    @property
    def net_exposure(self) -> float:
        return sum(self.weights.values())


# ==============================================================================
# Risk Engine Models
# ==============================================================================


@dataclass(frozen=True)
class RiskViolation:
    """Record of a risk limit violation."""

    rule_name: str
    description: str
    actual_value: float
    limit_value: float
    severity: str = "ERROR"  # "ERROR" or "WARNING"


@dataclass(frozen=True)
class RiskLimitConfig:
    """Configurable limits for the RiskEngine."""

    max_position_weight: float = 0.25
    max_gross_exposure: float = 1.00
    max_volatility: float = 0.20  # Annualized volatility ceiling
    max_drawdown: float = 0.15  # 15% max drawdown ceiling
    max_var_95: float = 0.05  # 5% daily VaR limit
    confidence_level: float = 0.95
    lookback_days: int = 252


@dataclass(frozen=True)
class DrawdownDetails:
    """Detailed drawdown tracking."""

    current_drawdown: float
    max_drawdown: float
    peak_equity: float
    trough_equity: float
    peak_date: datetime | None = None
    trough_date: datetime | None = None
    is_recovered: bool = False


@dataclass(frozen=True)
class RiskProfile:
    """Point-in-time risk evaluation of a portfolio or backtest."""

    timestamp: datetime
    var_95: float  # Historical VaR at configured confidence
    cvar_95: float  # Conditional VaR / Expected Shortfall
    volatility: float  # Annualized rolling volatility
    drawdown_details: DrawdownDetails
    gross_exposure: float
    net_exposure: float
    concentration_hhi: float  # Herfindahl-Hirschman Index
    beta: float | None = None
    correlations: dict[str, dict[str, float]] = field(default_factory=dict)
    verdict: RiskVerdict = RiskVerdict.APPROVED
    violations: list[RiskViolation] = field(default_factory=list)
